version: '3'
services:
  piwigo:
    container_name: piwigo
    image: piwigo-docker
    networks:
      - piwigo

  mysql:
    container_name: piwigo_mysql
    image: mysql:8.0.18
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - piwigo
    environment:
      MYSQL_USER: "${TAG_USER}"
      MYSQL_PASSWORD: "${TAG_PASSWORD}"
      MYSQL_DATABASE: "${TAG_DATABASE}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  nginx:
    image: nginx:latest
    container_name: nginx-piwigo 
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - piwigo
    links: 
      - piwigo
    ports:
      - 80:80
      

networks:
  piwigo:
